### ISSUE TITLE
How to run without CUDA

### ISSUE THREAD

**Issue by kabawo** [liamw96/pytorch.room.layout#4]
I get the following error due to lack of NVIDIA
`Traceback (most recent call last):
  File "segment_rl.py", line 792, in <module>
    main()
  File "segment_rl.py", line 788, in main
    test_seg(args)
  File "segment_rl.py", line 675, in test_seg
    model = torch.nn.DataParallel(single_model).cuda()
`
Is there a relevant flag to use? Thanks

**Comment by kabawo** [comment]
I have run the code successfully on another PC. It would still be nice to know, if it's a quick fix to run in CPU mode. Thanks
